### ISSUE TITLE
Rendering hangs and produced a PHP error?

### ISSUE THREAD

**Issue by anjackson** [machawk1/archivalAcidTest#1]
Perhaps I'm misunderstanding something, but http://acid.matkelly.com/ currently seems to hang, and produces this error in my browser console:

```
12:35:41.258 SyntaxError: expected expression, got '<'1 detect.js:1:0
```

Arising from likely-should-have-been-executed `<?php` text in acid.matkelly.com/WhichBrowser/detect.js?ua=Mozilla%2F5.0%20(Windows%20NT%206.1%3B%20WOW64%3B%20rv%3A41.0)%20Gecko%2F20100101%20Firefox%2F41.0&e=8&f=95&r=d8sppr&w=1920&h=1200

(on a side note, it would be good to understand whether index.html or index.php should be considered authoritative)

**Comment by machawk1** [comment]
@anjackson I get that error, too, in my JS console but still get satisfactory results in Google Chrome, OS X 10.11. What do you mean by it "hangs"? Does your browser give an indication that it's locked up? Two of the tests are dependent on JS processing (a timeout and scroll).

**Comment by anjackson** [comment]
Right, well, it was consistently hanging during rendering the second line of boxes (under the 'Javascript' heading). It's now totally fine.  No idea what was happening there - sorry to bother you!
